# User Guide

1. The first part below is for code testing line by line

2. The second part below is the complete code in a single run for single file analysis and batch analysis

# Preparing and testing codes

In [6]:
%pip install pandas

Requirement already satisfied: pandas in /Users/rainbow/opt/anaconda3/envs/fish/lib/python3.10/site-packages (2.1.4)
Requirement already satisfied: tzdata>=2022.1 in /Users/rainbow/opt/anaconda3/envs/fish/lib/python3.10/site-packages (from pandas) (2023.4)
Requirement already satisfied: pytz>=2020.1 in /Users/rainbow/opt/anaconda3/envs/fish/lib/python3.10/site-packages (from pandas) (2022.1)
Requirement already satisfied: numpy<2,>=1.22.4 in /Users/rainbow/opt/anaconda3/envs/fish/lib/python3.10/site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rainbow/opt/anaconda3/envs/fish/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/rainbow/opt/anaconda3/envs/fish/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [30]:
import pandas as pd

filename1 = '/Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map/datasets_mouse_brain_map_BrainReceptorShowcase_Slice1_Replicate1_cell_by_gene_S1R1_copy.csv'

cell_by_gene = pd.read_csv(filename1)
print(cell_by_gene)

                                    Unnamed: 0  Oxgr1  Htr1a  Htr1b  Htr1d  \
0      110883424764611924400221639916314253469    0.0    0.0    0.0    0.0
1      135188247894899244046039873973964001182    0.0    0.0    0.0    0.0
2      164766962839370328502017156371562646881    0.0    0.0    0.0    0.0
3      165747897693809971960756442245389760838    0.0    0.0    1.0    0.0
4      260943245639750847364278545493286724628    0.0    0.0    0.0    0.0
...                                        ...    ...    ...    ...    ...
78324  165273009496786595275688065919008183969    0.0    0.0    0.0    0.0
78325  250474226357477911702383283537224741401    0.0    0.0    0.0    0.0
78326   66106840181174834341279408890707577820    0.0    0.0    0.0    0.0
78327   66165211106933093510165165316573672348    0.0    0.0    0.0    0.0
78328   71051447268015582817266088343399517927    0.0    0.0    0.0    0.0

       Htr1f  Htr2a  Htr2b  Htr2c  Htr4  ...  Blank-156  Blank-157  Blank-158  \
0        0.0    0.0    0.0    0.0   0.0  ...        0.0        0.0        0.0
1        0.0    0.0    0.0    0.0   0.0  ...        0.0        0.0        0.0
2        0.0    0.0    0.0    0.0   0.0  ...        0.0        0.0        0.0
3        0.0    0.0    0.0    0.0   0.0  ...        0.0        0.0        0.0
4        0.0    0.0    0.0    0.0   0.0  ...        0.0        0.0        0.0
...      ...    ...    ...    ...   ...  ...        ...        ...        ...
78324    0.0    0.0    0.0    0.0   0.0  ...        0.0        0.0        0.0
78325    0.0    0.0    0.0    0.0   0.0  ...        0.0        0.0        0.0
78326    0.0    0.0    0.0    0.0   0.0  ...        0.0        0.0        0.0
78327    0.0    0.0    0.0    0.0   0.0  ...        0.0        0.0        0.0
78328    0.0    0.0    0.0    0.0   0.0  ...        0.0        0.0        0.0

       Blank-159  Blank-160  Blank-161  Blank-162  Blank-163  Blank-164  \
0            0.0        0.0        0.0        0.0        0.0        0.0
1            0.0        0.0        0.0        0.0        0.0        0.0
2            0.0        0.0        0.0        0.0        0.0        0.0
3            0.0        0.0        0.0        0.0        0.0        0.0
4            1.0        0.0        0.0        0.0        0.0        0.0
...          ...        ...        ...        ...        ...        ...
78324        0.0        0.0        0.0        0.0        0.0        0.0
78325        0.0        0.0        0.0        0.0        0.0        0.0
78326        0.0        0.0        0.0        0.0        0.0        0.0
78327        0.0        0.0        0.0        0.0        0.0        0.0
78328        0.0        0.0        0.0        0.0        0.0        0.0

       Blank-165
0            0.0
1            0.0
2            0.0
3            0.0
4            0.0
...          ...
78324        0.0
78325        0.0
78326        0.0
78327        0.0
78328        0.0

[78329 rows x 650 columns]

In [23]:
cell_by_gene = cell_by_gene.rename(columns = {'Unnamed: 0': 'Cell_ID'})
cell_by_gene

,Cell_ID,Oxgr1,Htr1a,Htr1b,Htr1d,Htr1f,Htr2a,Htr2b,Htr2c,Htr4,...,Blank-156,Blank-157,Blank-158,Blank-159,Blank-160,Blank-161,Blank-162,Blank-163,Blank-164,Blank-165
0,110883424764611924400221639916314253469,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,135188247894899244046039873973964001182,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,164766962839370328502017156371562646881,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,165747897693809971960756442245389760838,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,260943245639750847364278545493286724628,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78324,165273009496786595275688065919008183969,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78325,250474226357477911702383283537224741401,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78326,66106840181174834341279408890707577820,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78327,66165211106933093510165165316573672348,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78328,71051447268015582817266088343399517927,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
# remove the index column: Cell_ID
cell_by_gene2 = cell_by_gene.loc[:, "Oxgr1":"Blank-160"]
cell_by_gene2

,Oxgr1,Htr1a,Htr1b,Htr1d,Htr1f,Htr2a,Htr2b,Htr2c,Htr4,Htr5a,...,Blank-151,Blank-152,Blank-153,Blank-154,Blank-155,Blank-156,Blank-157,Blank-158,Blank-159,Blank-160
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78324,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78325,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78327,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78328,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
cell_by_gene2_rowsum = cell_by_gene2.sum(axis=1)
cell_by_gene2_rowsum

0         68.0
1        178.0
2        179.0
3        401.0
4        303.0
         ...
78324     85.0
78325    396.0
78326    139.0
78327    144.0
78328    300.0
Length: 78329, dtype: float64

In [35]:
cell_by_gene2_rowsum.describe()

count    78329.000000
mean       368.644653
std        298.639149
min         50.000000
25%        147.000000
50%        269.000000
75%        512.000000
max       2255.000000
dtype: float64

In [29]:
import pandas as pd

filename2 = '/Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map/datasets_mouse_brain_map_BrainReceptorShowcase_Slice1_Replicate1_cell_metadata_S1R1.csv'

cell_metadata = pd.read_csv(filename2)
print(cell_metadata)

                                    Unnamed: 0   fov       volume  \
0      110883424764611924400221639916314253469     0   432.141425
1      135188247894899244046039873973964001182     0  1351.802616
2      164766962839370328502017156371562646881     0  1080.653268
3      165747897693809971960756442245389760838     0  1652.000749
4      260943245639750847364278545493286724628     0  1343.378642
...                                        ...   ...          ...
78324  165273009496786595275688065919008183969  1225  1159.623218
78325  250474226357477911702383283537224741401  1225  1058.062257
78326   66106840181174834341279408890707577820  1225  1155.306779
78327   66165211106933093510165165316573672348  1225   394.808108
78328   71051447268015582817266088343399517927  1225   798.608811

          center_x     center_y        min_x        max_x        min_y  \
0       156.563284  4271.326432   151.530484   161.596084  4264.619632
1       156.509284  4256.962431   148.290484   164.728084  4247.663631
2       159.965284  4228.180431   152.178484   167.752084  4220.555630
3       167.579284  4323.868433   158.226484   176.932084  4314.191633
4       160.559284  4308.802433   152.394484   168.724084  4301.231633
...            ...          ...          ...          ...          ...
78324  9154.007886  4445.528506  9143.953086  9164.062686  4435.473706
78325  9088.829884  4423.712505  9081.097084  9096.562685  4416.249705
78326  9170.261887  4431.758506  9159.613086  9180.910687  4421.217705
78327  9086.183884  4417.016505  9081.745084  9090.622685  4412.253705
78328  9073.169884  4419.770505  9065.005084  9081.334684  4414.521705

             max_y
0      4278.033232
1      4266.261232
2      4235.805231
3      4333.545233
4      4316.373233
...            ...
78324  4455.583306
78325  4431.175306
78326  4442.299306
78327  4421.779305
78328  4425.019305

[78329 rows x 9 columns]

In [31]:
cell_metadata = cell_metadata.rename(columns = {'Unnamed: 0': 'Cell_ID'})
cell_metadata

,Cell_ID,fov,volume,center_x,center_y,min_x,max_x,min_y,max_y
0,110883424764611924400221639916314253469,0,432.141425,156.563284,4271.326432,151.530484,161.596084,4264.619632,4278.033232
1,135188247894899244046039873973964001182,0,1351.802616,156.509284,4256.962431,148.290484,164.728084,4247.663631,4266.261232
2,164766962839370328502017156371562646881,0,1080.653268,159.965284,4228.180431,152.178484,167.752084,4220.555630,4235.805231
3,165747897693809971960756442245389760838,0,1652.000749,167.579284,4323.868433,158.226484,176.932084,4314.191633,4333.545233
4,260943245639750847364278545493286724628,0,1343.378642,160.559284,4308.802433,152.394484,168.724084,4301.231633,4316.373233
...,...,...,...,...,...,...,...,...,...
78324,165273009496786595275688065919008183969,1225,1159.623218,9154.007886,4445.528506,9143.953086,9164.062686,4435.473706,4455.583306
78325,250474226357477911702383283537224741401,1225,1058.062257,9088.829884,4423.712505,9081.097084,9096.562685,4416.249705,4431.175306
78326,66106840181174834341279408890707577820,1225,1155.306779,9170.261887,4431.758506,9159.613086,9180.910687,4421.217705,4442.299306
78327,66165211106933093510165165316573672348,1225,394.808108,9086.183884,4417.016505,9081.745084,9090.622685,4412.253705,4421.779305
78328,71051447268015582817266088343399517927,1225,798.608811,9073.169884,4419.770505,9065.005084,9081.334684,4414.521705,4425.019305

In [38]:
cell_metadata['volume'].describe()

count    78329.000000
mean       828.066416
std        426.315232
min         20.106929
25%        493.926452
50%        814.047282
75%       1128.464415
max       1999.859738
Name: volume, dtype: float64

In [43]:
# transcript_by_volume_and_cell

transcript_volume_cell = cell_by_gene2_rowsum/cell_metadata['volume']
print(transcript_volume_cell)

transcript_volume_cell.describe()

0        0.157356
1        0.131676
2        0.165641
3        0.242736
4        0.225551
           ...
78324    0.073300
78325    0.374269
78326    0.120314
78327    0.364734
78328    0.375653
Length: 78329, dtype: float64

count    78329.000000
mean         0.450154
std          0.233039
min          0.029647
25%          0.269520
50%          0.418728
75%          0.596353
max          2.693090
dtype: float64

# Complete code

In [46]:
# for one file analysis only

import pandas as pd

filename1 = '/Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map/datasets_mouse_brain_map_BrainReceptorShowcase_Slice1_Replicate1_cell_by_gene_S1R1.csv'

cell_by_gene = pd.read_csv(filename1)
#print(cell_by_gene)

cell_by_gene = cell_by_gene.rename(columns = {'Unnamed: 0': 'Cell_ID'})
#cell_by_gene

# remove the index column: Cell_ID
cell_by_gene2 = cell_by_gene.loc[:, "Oxgr1":"Blank-160"]
#cell_by_gene2

cell_by_gene2_rowsum = cell_by_gene2.sum(axis=1)
#cell_by_gene2_rowsum
#cell_by_gene2_rowsum.describe()


filename2 = '/Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map/datasets_mouse_brain_map_BrainReceptorShowcase_Slice1_Replicate1_cell_metadata_S1R1.csv'

cell_metadata = pd.read_csv(filename2)
#print(cell_metadata)

cell_metadata = cell_metadata.rename(columns = {'Unnamed: 0': 'Cell_ID'})
#cell_metadata

#cell_metadata['volume'].describe()

# transcript_by_volume_and_cell

transcript_volume_cell = cell_by_gene2_rowsum/cell_metadata['volume']
print(transcript_volume_cell)

transcript_volume_cell.describe()

0        0.157356
1        0.131676
2        0.165641
3        0.242736
4        0.225551
           ...
78324    0.073300
78325    0.374269
78326    0.120314
78327    0.364734
78328    0.375653
Length: 78329, dtype: float64

count    78329.000000
mean         0.450154
std          0.233039
min          0.029647
25%          0.269520
50%          0.418728
75%          0.596353
max          2.693090
dtype: float64

In [65]:
# Batch analysis

path = "/Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map"

file_path = "datasets_mouse_brain_map_BrainReceptorShowcase_Slice" 

for i in [1,2,3]:
    files_1 = path + '/' + file_path + str(i) + '_Replicate1_cell_' + 'by_gene_S' + str(i) + 'R1.csv'
    print(files_1)
    #print(files_1 == filename1)
    files_2 = path + '/' + file_path + str(i) + '_Replicate1_cell_metadata_S' + str(i) + 'R1.csv'
    print(files_2)
    #print(files_2 == filename2)
    
    cell_by_gene = pd.read_csv(files_1)
    #print(cell_by_gene)

    cell_by_gene = cell_by_gene.rename(columns = {'Unnamed: 0': 'Cell_ID'})
    #cell_by_gene

    # remove the index column: Cell_ID
    cell_by_gene2 = cell_by_gene.loc[:, "Oxgr1":"Blank-160"]
    #cell_by_gene2

    cell_by_gene2_rowsum = cell_by_gene2.sum(axis=1)
    
    cell_metadata = pd.read_csv(files_2)
    #print(cell_metadata)

    cell_metadata = cell_metadata.rename(columns = {'Unnamed: 0': 'Cell_ID'})
    #cell_metadata

    #cell_metadata['volume'].describe()

    # transcript_by_volume_and_cell

    transcript_volume_cell = cell_by_gene2_rowsum/cell_metadata['volume']
    
    print(transcript_volume_cell)

    print(transcript_volume_cell.describe())

/Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map/datasets_mouse_brain_map_BrainReceptorShowcase_Slice1_Replicate1_cell_by_gene_S1R1.csv
/Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map/datasets_mouse_brain_map_BrainReceptorShowcase_Slice1_Replicate1_cell_metadata_S1R1.csv
0        0.157356
1        0.131676
2        0.165641
3        0.242736
4        0.225551
           ...
78324    0.073300
78325    0.374269
78326    0.120314
78327    0.364734
78328    0.375653
Length: 78329, dtype: float64
count    78329.000000
mean         0.450154
std          0.233039
min          0.029647
25%          0.269520
50%          0.418728
75%          0.596353
max          2.693090
dtype: float64
/Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map/datasets_mouse_brain_map_BrainReceptorShowcase_Slice2_Replicate1_cell_by_gene_S2R1.csv
/Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map/datasets_mouse_brain_map_BrainReceptorShowcase_Slice2_Replicate1_cell_metadata_S2R1.csv
0        0.160743
1        0.050577
2        0.076070
3        0.096036
4        0.074549
           ...
83541    0.048916
83542    0.056607
83543    0.078622
83544    0.057113
83545    0.102282
Length: 83546, dtype: float64
count    83546.000000
mean         0.359678
std          0.194924
min          0.025692
25%          0.208558
50%          0.326028
75%          0.480814
max          2.318072
dtype: float64
/Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map/datasets_mouse_brain_map_BrainReceptorShowcase_Slice3_Replicate1_cell_by_gene_S3R1.csv
/Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map/datasets_mouse_brain_map_BrainReceptorShowcase_Slice3_Replicate1_cell_metadata_S3R1.csv
0        0.175144
1        0.075031
2        0.181934
3        0.164655
4        0.187881
           ...
70839    0.424589
70840    0.491106
70841    0.274191
70842    0.084795
70843    0.240824
Length: 70844, dtype: float64
count    70844.000000
mean         0.452752
std          0.223575
min          0.028610
25%          0.275417
50%          0.434712
75%          0.599069
max          3.122480
dtype: float64

In [49]:
# import OS module
import os
# Get the list of all files and directories
path = "/Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map"
dir_list = os.listdir(path)
print("Files and directories in '", path, "' :")
# prints all files
print(dir_list)
type(dir_list)

Files and directories in ' /Users/rainbow/Documents/Image_data/MERFISH_Mouse_Brain_Receptor_Map ' :
['datasets_mouse_brain_map_BrainReceptorShowcase_Slice2_Replicate1_cell_by_gene_S2R1.csv', 'datasets_mouse_brain_map_BrainReceptorShowcase_Slice1_Replicate1_cell_by_gene_S1R1_copy.csv', '.DS_Store', 'datasets_mouse_brain_map_BrainReceptorShowcase_Slice1_Replicate1_cell_by_gene_S1R1.csv', 'datasets_mouse_brain_map_BrainReceptorShowcase_Slice3_Replicate1_cell_metadata_S3R1.csv', 'datasets_mouse_brain_map_BrainReceptorShowcase_Slice2_Replicate1_cell_metadata_S2R1.csv', 'datasets_mouse_brain_map_BrainReceptorShowcase_Slice1_Replicate1_cell_metadata_S1R1.csv', 'datasets_mouse_brain_map_BrainReceptorShowcase_Slice3_Replicate1_cell_by_gene_S3R1.csv']

list

In [52]:
for i in [1,2,3]:
    print(i)

1
2
3